[package]
name = "fhirbolt"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision", "preserve_order"] }
quick-xml = "0.25"

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
zip = { version = "0.6", features = ["deflate"] }