[workspace]
members = [
    "fhirbolt",
    "fhirbolt-codegen",
    "fhirbolt-model",
    "fhirbolt-element",
    "fhirbolt-serde",
    "fhirbolt-path",
    "fhirbolt-shared",
    "tests",
    "benches",
    "examples/*"
]
