[package]
name = "fhirbolt-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
quick-xml = "0.25"

fhirbolt-shared = { path = "../fhirbolt-shared" }
