[package]
name = "fhirbolt-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
quick-xml = "0.25"

fhirbolt-shared = { path = "../fhirbolt-shared" }

[dev-dependencies]
# used by doc-tests
fhirbolt = { path = "../fhirbolt", features = ["r4b"] }