[package]
name = "fhirbolt-shared"
version = "0.1.0"
edition = "2021"

[features]
default = ["path"]
path = ["serde_helpers"]
serde_helpers = []

[dependencies]
phf = { version = "0.11", features = ["macros"] }
