[package]
name = "benches"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
criterion = "0.4"

fhirbolt = { path = "../fhirbolt", features = ["r4"] }
tests = { path = "../tests" }

[[bench]]
name = "bench_serde"
path = "bench_serde.rs"
harness = false
