name: Benchmark PR

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_r4:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Build
        run: cargo build -p fhirbolt --features r4 --release --verbose

  build_bench_serde:
    needs: build_r4
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Build
        run: cargo build --bench bench_serde --release --verbose --jobs 1

  bench_serde:
    needs: build_bench_serde
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - uses: boa-dev/criterion-compare-action@v3
        with:
          benchName: bench_serde
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
