name: Benchmark PR

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Build
        run: cargo build --all-features --release --verbose

  bench_serde:
    needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - uses: boa-dev/criterion-compare-action@v3
        with:
          benchName: bench_serde
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
