name: Codegen Version

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  version_bumped:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: SebRollen/toml-action@v1.0.1
        id: main_version
        with:
          file: fhirbolt-codegen/Cargo.toml
          field: package.version

      - uses: actions/checkout@v3
      - uses: SebRollen/toml-action@v1.0.1
        id: this_version
        with:
          file: fhirbolt-codegen/Cargo.toml
          field: package.version

      - name: Check fhirbolt-codegen version updated if generated code changed
        run: |
          shopt -s globstar

          if git diff --quiet HEAD origin/main -- **/generated/ ; then
            echo No changes in generated code detected
            exit 0
          else
            echo Changes in generated code detected
            if [ ${{steps.main_version.outputs.value}} != ${{steps.this_version.outputs.value}} ]; then
              echo fhirbolt-codegen version was updated
              exit 0
            else
              echo fhirbolt-codegen version was not updated
              exit 1
            fi
          fi
      - name: Check generated code has correct version (fhirbolt-codegen was run)
        run: |
          if grep -q v${{steps.this_version.outputs.value}} fhirbolt-model/src/generated/r4/resource.rs ; then
              echo Generated code has correct fhirbolt-codegen version
              exit 0
          else
              echo Generated code does not have correct fhirbolt-codegen version
              exit 1
          fi