name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_codegen:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Build
        run: cargo build -p fhirbolt-codegen --release --verbose

  build_r4:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Build
        run: cargo build -p fhirbolt --features r4 --release --verbose

  build_r4b:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Build
        run: cargo build -p fhirbolt --features r4b --release --verbose

  build_r5:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Build
        run: cargo build -p fhirbolt --features r5 --release --verbose

  clippy_check:
    needs: [build_codegen, build_r4, build_r4b, build_r5]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  unit_tests:
    needs: [build_codegen, build_r4, build_r4b, build_r5]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test --lib
  
  doc_tests:
    needs: [build_codegen, build_r4, build_r4b, build_r5]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test --doc
  
  test_serde_json_r4:
    needs: build_r4
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test -p tests --test test_serde_json --features r4 --release --verbose
  
  test_serde_xml_r4:
    needs: build_r4
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test -p tests --test test_serde_xml --features r4 --release --verbose
  
  test_serde_json_r4b:
    needs: build_r4b
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test -p tests --test test_serde_json --features r4b --release --verbose
  
  test_serde_xml_r4b:
    needs: build_r4b
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test -p tests --test test_serde_xml --features r4b --release --verbose
  
  test_serde_json_r5:
    needs: build_r5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test -p tests --test test_serde_json --features r5 --release --verbose
  
  test_serde_xml_r5:
    needs: build_r5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run tests
        run: cargo test -p tests --test test_serde_xml --features r5 --release --verbose

  benchmark:
    needs: [build_codegen, build_r4, build_r4b, build_r5]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
      - name: Run benches
        run: cargo bench -p benches --verbose
